name: gbedu
description: Afrobeats music maker app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  audioplayers: ^0.15.0
  gapless_audio_loop: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/bass/
    - assets/beat/
    - assets/fx/
    - assets/perc/
    - assets/synth/
    - assets/vox/